### ISSUE TITLE
Complete task - Task list

### ISSUE THREAD

**Issue by reynisson** [SCS-ASSE-FS21-Group1/tapas#15]
**Acceptance criteria:**
- [x]  Implement the CompleteTask REST call that takes as parameters: _Task ID, Task Result (JSON)?_
  - [x] Set the task status to EXECUTED and the Task result to _Task Result (JSON)?_
  - [x] Send a success message back
