### ISSUE TITLE
Identify potential executors (TODO)

### ISSUE THREAD

**Issue by reynisson** [SCS-ASSE-FS21-Group1/tapas#8]
**Acceptance criteria:**
- [ ]  Implement the FindExecutor REST call that takes as parameters: _Task ID, Task Type, Task Options (JSON)_
  - [ ] Query the executor pool via GetExecutorsForTaskType(Task Type). 
    - [ ] If 1 or more executors are returned then add the (_Task ID, Task Type, Task Options (JSON)_) to the task queue (internal dictionary of queues?). 
      - [ ] Then notify all executors returned that there is a new task on the task list via TODO FILL IN
    - [ ] Else if no executors are returned, then respond with a descriptive error message
