### ISSUE TITLE
Delete task from task queue TODO

### ISSUE THREAD

**Issue by reynisson** [SCS-ASSE-FS21-Group1/tapas#9]
**Acceptance criteria:**
- [x]  Implement the RemoveTaskFromTaskQueue REST call that takes as parameters: _Task ID_
  - [x] Validate that the _Task ID_ is contained within the Task queue
  - [x] If so, then remove the task with the _Task ID_ from the task queue
  - [x] If not then return a TaskIDNotFoundInTaskQueue error - (distinguish between the case where the Task ID is being worked on and then its just invalid)
  - [x] If the removal was successful then return a success message
